title: International Press journal SII author support
description: TeX related material for the manuscript preparation for the 
             International Press journal Statistics and Its Interface 
             (SII)
show_downloads: true
theme: jekyll-theme-tactile
